on:  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: arm-none-eabi-gcc
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10-2021.10'

    - name: Build binary
      run: |
        cd firmware
        make -j4
    
    - name: Build c App
      run: |
        sudo apt update -y
        sudo apt install -y libserialport-dev 
        cd app/c
        make -j4
